using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EVSTAR.Models
{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse); 
    public class FutureDial
    {
        public string _id { get; set; }
        public string amperage { get; set; }
        public string UserDomainName { get; set; }
        public string RealDoSkipwelcome_NB { get; set; }
        public string FunctionTestFailedTestItems { get; set; }
        public string BatteryCurrentCapacity { get; set; }
        public string showCertificateLink { get; set; }
        public string errorCode { get; set; }
        public string batteryCycleCount { get; set; }
        public string SIMExist { get; set; }
        public string FT_GRADE_COMMENT_Question2 { get; set; }
        public string FT_GRADE_COMMENT_Question1 { get; set; }
        public string functionTestProfile { get; set; }
        public string batterylevel { get; set; }
        public string OriginalFrontCameraSerial { get; set; }
        public DateTime serverTime { get; set; }
        public string sourcePhoneID { get; set; }
        public string FunctionTestFailedTestItems4Printer { get; set; }
        public string operationSystem { get; set; }
        public string endDetectTime { get; set; }
        public string ErrList { get; set; }
        public string FT_PROXIMITY_SENSOR_TEST { get; set; }
        public string devicememorysize { get; set; }
        public string functionTestResult { get; set; }
        public string activationState { get; set; }
        public string endDeviceMode { get; set; }
        public string UpdatedFrontCameraSerial { get; set; }
        public string BackCameraSerialNumber { get; set; }
        public string productid { get; set; }
        public string wsid { get; set; }
        public string readMEID_IMEIFail { get; set; }
        public string FT_DEVICE_INFO { get; set; }
        public string FT_Profile_name { get; set; }
        public string assistiveTouch { get; set; }
        public string BatteryDesignCapacity { get; set; }
        public string FT_GRADE_COMMENT_Answer1 { get; set; }
        public string FD_MEID { get; set; }
        public string FT_FINGERPRINT_SIMPLE { get; set; }
        public string FingerPrintSerialNumber { get; set; }
        public string FT_COMPUTER_USB_PLUG_TEST { get; set; }
        public string OriginalBatterySerial { get; set; }
        public string info_RealDoActive { get; set; }
        public string ManufactureDate { get; set; }
        public string ProductVer { get; set; }
        public string info_RealDoSkipwelcome { get; set; }
        public string SystemDirectory { get; set; }
        public string operatorName { get; set; }
        public string FT_FINGERPRINT { get; set; }
        public string MacAddress { get; set; }
        public string installFDProfile { get; set; }
        public string BatterySerialNumber { get; set; }
        public string FT_LCD_FILL_TEST2 { get; set; }
        public string FindMyiPhoneSource { get; set; }
        public string beginDetectTime { get; set; }
        public string workstationName { get; set; }
        public string fastWipeESim { get; set; }
        public string deviceType { get; set; }
        public string FTAppVersion { get; set; }
        public string IPSWFile { get; set; }
        public string wsgroupid { get; set; }
        public string value_FDVerifyUserInput { get; set; }
        public string Org_BackCameraSerialNumber { get; set; }
        public string OriginalBackCameraSerial { get; set; }
        public string mvdResult { get; set; }
        public string sourceMake { get; set; }
        public string UpdatedBatterySerial { get; set; }
        public string UpdatedBackCameraSerial { get; set; }
        public string PCName { get; set; }
        public string OriginalFingerprintSerial { get; set; }
        public string Battery { get; set; }
        public string Org_LCDSerialNumber { get; set; }
        public string sourceModel { get; set; }
        public string StartTime { get; set; }
        public string UserName { get; set; }
        public string RegulatoryModelNumber { get; set; }
        public string batterySerial { get; set; }
        public string color { get; set; }
        public string wattage { get; set; }
        public string Org_FrontCameraSerialNumber { get; set; }
        public string BatteryManufactureDate { get; set; }
        public string portNumber { get; set; }
        public string DetectSpendTime { get; set; }
        public string @operator { get; set; }
        public string EndTime { get; set; }
        public string startiOSVersion { get; set; }
        public string mvdInfo { get; set; }
        public string systemAllMacAddrs { get; set; }
        public string dec_meid_imei { get; set; }
        public string batteryReplaced { get; set; }
        public string RealDoActive { get; set; }
        public string sourceCarrier { get; set; }
        public string SerialNumber { get; set; }
        public string value_FDVerifyExtraInfo { get; set; }
        public string company { get; set; }
        public string FD_IMEI { get; set; }
        public string Org_MLBSerialNumber { get; set; }
        public string autoopenwifi { get; set; }
        public string FDResult { get; set; }
        public string logicalDrives_0 { get; set; }
        public string BatteryFullChargeCapacity { get; set; }
        public string FunctionTestFinalResult { get; set; }
        public string FT_WIFI { get; set; }
        public string barCode { get; set; }
        public string SystemMacAddress { get; set; }
        public string jailbroken { get; set; }
        public string CurrentSystemMacAddress { get; set; }
        public string systemVersion { get; set; }
        public string OriginalMLBSerial { get; set; }
        public string PhoneNumer1 { get; set; }
        public string PhoneNumer2 { get; set; }
        public string serialnumber { get; set; }
        public string site { get; set; }
        public string ProcessorCount { get; set; }
        public string FindMyiPhone { get; set; }
        public string endiOSVersion { get; set; }
        public string SystemPageSize { get; set; }
        public string iccid { get; set; }
        public string bluetoothaddr { get; set; }
        public string Org_BatterySerialNumber { get; set; }
        public string esnNumber { get; set; }
        public string LCDSerial { get; set; }
        public string MLBSerialNumber { get; set; }
        public string UpdatedMLBSerial { get; set; }
        public string FT_GRADE_COMMENT_Answer2 { get; set; }
        public string UpdatedBatteryManufactureDate { get; set; }
        public string iosVersion { get; set; }
        public string startDeviceMode { get; set; }
        public string DeviceOS { get; set; }
        public DateTime timeCreated { get; set; }
        public string pESN { get; set; }
        public string modelnumber { get; set; }
        public string carrierSource { get; set; }
        public string BatteryRatio { get; set; }
        public string FT_HOME_KEY_TEST { get; set; }
        public string Error_code_detail { get; set; }
        public string Org_FingerPrintSerialNumber { get; set; }
        public string FrontCameraSerialNumber { get; set; }
        public string BatteryNominalChargeCapacity { get; set; }
        public string timetaken { get; set; }
        public string UDID { get; set; }
        public string S3Level { get; set; }
        public string iCloud { get; set; }
        public string stopOnSim { get; set; }
        public string saveXmlPath { get; set; }
        public string fastWipe { get; set; }
        public DateTime _created { get; set; }
        public DateTime _updated { get; set; }
        public string _etag { get; set; }
    }

}